### ISSUE TITLE
This is Awesome!  So helpful in debugging my HCE app.

### ISSUE THREAD

**Issue by handstandsam** [doc-rj/smartcard-reader#2]
Are you planning on putting this up on the Google Play Store?

**Comment by doc-rj** [comment]
Glad it's useful for your testing!  Play store is not a bad idea, but I haven't put much thought into it. A little concerned that the target audience would be too limited, you know what I mean? If you're open to sharing, what kind of app are you working on?

**Comment by handstandsam** [comment]
True, the audience is niche, but always looks good to have an app on the play store.  This app is helpful because I am developing an HCE payment app and I wanted to figure out how to trigger the SELECT PPSE command from an android. I had been using a USB reader or a vending machine to trigger my HCE app to launch before. Your app allows me to tap 2 devices together instead and see some extra debug info. I stumbled upon your app by searching github for the SELECT command byte array in Java code.

**Comment by doc-rj** [comment]
Cool, please let me know if you have any ideas or feature requests for smartcard-reader... About your app, you've got me a little curious. There aren't many people out there working on HCE payment apps. I'd be interested if and when you are free to share more.
