### ISSUE TITLE
Failed to resolve: com.afollestad.material-dialogs:0.7.5.1

### ISSUE THREAD

**Issue by vectorialgradha** [doc-rj/smartcard-reader#4]
Trying a clean checkout fails compilation in Android studio.

![captura de pantalla 2015-11-04 a las 11 55 18](https://cloud.githubusercontent.com/assets/11269962/10936177/59ca59d2-82eb-11e5-9aad-27104e633203.png)

**Comment by doc-rj** [comment]
thanks, merged pull request
